In [1]:
import numpy as np
import pandas as pd
DIMS = (18,11)

In [2]:
cols = []
for i in range(DIMS[0]):
    for j in range(DIMS[1]):
        cols.append((i,j))
df = pd.read_csv('datasets/flattenedClimbs.csv', header=None).astype(bool)
df.columns = cols
df

,"(0, 0)","(0, 1)","(0, 2)","(0, 3)","(0, 4)","(0, 5)","(0, 6)","(0, 7)","(0, 8)","(0, 9)",...,"(17, 1)","(17, 2)","(17, 3)","(17, 4)","(17, 5)","(17, 6)","(17, 7)","(17, 8)","(17, 9)","(17, 10)"
0,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11901,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11902,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
11903,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
11904,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11905,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [3]:
df['holds'] = df.apply(lambda row: list(row[row].index), axis=1)
df

,"(0, 0)","(0, 1)","(0, 2)","(0, 3)","(0, 4)","(0, 5)","(0, 6)","(0, 7)","(0, 8)","(0, 9)",...,"(17, 2)","(17, 3)","(17, 4)","(17, 5)","(17, 6)","(17, 7)","(17, 8)","(17, 9)","(17, 10)",holds
0,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 2), (2, 6), (5, 5), (9, 7), (11, 1), (11,..."
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 4), (4, 0), (7, 3), (10, 2), (14, 6), (16..."
2,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 6), (3, 4), (5, 6), (7, 4), (9, 6), (10, ..."
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 3), (2, 4), (5, 2), (8, 7), (10, 4), (14,..."
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,"[(0, 8), (4, 10), (7, 3), (9, 8), (11, 8), (14..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11901,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 6), (3, 3), (6, 4), (8, 4), (10, 9), (14,..."
11902,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 7), (2, 3), (5, 3), (7, 4), (13, 5)]"
11903,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,"[(0, 8), (2, 9), (3, 4), (3, 8), (4, 4), (7, 1..."
11904,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 10), (2, 9), (3, 4), (3, 8), (4, 4), (7, ..."
11905,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,"[(0, 6), (1, 6), (3, 0), (6, 4), (10, 3), (11,..."

In [4]:
grades = pd.read_csv('datasets/grades.txt', names=['grade'])
grades
df = pd.concat((df, grades), axis=1, sort=False)
df

,"(0, 0)","(0, 1)","(0, 2)","(0, 3)","(0, 4)","(0, 5)","(0, 6)","(0, 7)","(0, 8)","(0, 9)",...,"(17, 3)","(17, 4)","(17, 5)","(17, 6)","(17, 7)","(17, 8)","(17, 9)","(17, 10)",holds,grade
0,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,"[(0, 2), (2, 6), (5, 5), (9, 7), (11, 1), (11,...",12
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,"[(0, 4), (4, 0), (7, 3), (10, 2), (14, 6), (16...",5
2,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,"[(0, 6), (3, 4), (5, 6), (7, 4), (9, 6), (10, ...",4
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,"[(0, 3), (2, 4), (5, 2), (8, 7), (10, 4), (14,...",4
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,"[(0, 8), (4, 10), (7, 3), (9, 8), (11, 8), (14...",16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11901,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,"[(0, 6), (3, 3), (6, 4), (8, 4), (10, 9), (14,...",7
11902,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,"[(0, 7), (2, 3), (5, 3), (7, 4), (13, 5)]",8
11903,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,"[(0, 8), (2, 9), (3, 4), (3, 8), (4, 4), (7, 1...",5
11904,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,"[(0, 10), (2, 9), (3, 4), (3, 8), (4, 4), (7, ...",5
11905,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,"[(0, 6), (1, 6), (3, 0), (6, 4), (10, 3), (11,...",12

In [5]:
def find_orange(hld, hlds):
    i = hld[0]
    hold = hld[1:]
    below = hlds[i+1:,1:]
    j = i-1
    while j >= 0 and hlds[j][1] == hold[0]:
        below = np.concatenate(([hlds[j,1:]], below))
        j -= 1
    if below.shape[0] == 0:
        return np.array([np.nan, np.nan])
    dists = np.sqrt((hold[0]-below[:,0])**2+(hold[1]-below[:,1])**2)
    weights = 1/dists
    orange = np.dot(weights, below)/(weights.sum())
    return orange

In [6]:
def find_quad(row):
    slope = row[4]
    if slope == 0:
        if row[3] > row[1]:
            return 3
        else:
            return 0
    if slope == np.inf or slope == -np.inf:
        return 1
    if slope > 0:
        if slope <= 1:
            return 0
        else:
            return 1
    else:
        if slope <= -1:
            return 2
        else:
            return 3

In [7]:
def for_each_climb(row):
    orig = np.array(row.holds)
    grade = row.grade
    idx = np.arange(orig.shape[0]).reshape(orig.shape[0],1)
    holds = np.concatenate((idx, orig), axis=1)
    orange = np.apply_along_axis(find_orange, 1, holds, holds)
    hold_orange = np.concatenate((orig, orange), axis=1)
    slopes = -(hold_orange[:,2]-hold_orange[:,0])/(hold_orange[:,3]-hold_orange[:,1])
    hold_slope = np.concatenate((hold_orange, slopes.reshape(slopes.shape[0], 1)), axis=1)
    quads = np.apply_along_axis(find_quad, 1, hold_slope)
    hold_quad = np.concatenate((orig, quads.reshape(slopes.shape[0], 1)), axis=1)
    for row in hold_quad:
        master[row[0],row[1],row[2],0] += grade
        master[row[0],row[1],row[2],1] += 1

In [8]:
master = np.zeros((18,11,4,2))
df.apply(for_each_climb, axis=1)

<ipython-input-7-9141850b2f97>:8: RuntimeWarning: divide by zero encountered in true_divide
  slopes = -(hold_orange[:,2]-hold_orange[:,0])/(hold_orange[:,3]-hold_orange[:,1])
<ipython-input-7-9141850b2f97>:8: RuntimeWarning: invalid value encountered in true_divide
  slopes = -(hold_orange[:,2]-hold_orange[:,0])/(hold_orange[:,3]-hold_orange[:,1])

0        None
1        None
2        None
3        None
4        None
         ...
11901    None
11902    None
11903    None
11904    None
11905    None
Length: 11906, dtype: object

In [9]:
classifier = master[:,:,:,0]/master[:,:,:,1]
classifier

<ipython-input-9-5294cb8ed992>:1: RuntimeWarning: invalid value encountered in true_divide
  classifier = master[:,:,:,0]/master[:,:,:,1]

array([[[        nan,  7.        ,  7.28851175,  8.31428571],
        [        nan,  5.        ,  6.37984496,  6.4       ],
        [        nan,  7.04761905,  8.07401813,  8.33333333],
        [        nan,  5.84836066,  6.52179034,  6.        ],
        [        nan,  5.93142857,  5.71923077,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,  6.068     ,  5.56181319,         nan],
        [        nan,  8.14612676,  7.84848485,         nan],
        [ 6.        ,  6.49897471,  5.98076923,         nan],
        [        nan,         nan,         nan,         nan],
        [ 8.        ,  7.391133  ,  4.        ,         nan]],

       [[        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,  5.57746479,  5.72654155,  7.        ],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,  5.93536804,  5.77152318,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan]],

       [[        nan,  7.        ,  7.47058824,  7.6       ],
        [        nan,  6.5       ,  5.6146789 ,  6.4       ],
        [        nan,  5.4       ,  6.71523179,  6.        ],
        [        nan,  7.45      ,  7.9847561 ,  9.8       ],
        [        nan,  5.84300341,  5.86533333,         nan],
        [        nan,  6.39487179,  6.22527473,         nan],
        [        nan,  8.4180791 ,  8.35616438,         nan],
        [        nan,  6.5619195 ,  6.02173913,         nan],
        [ 5.75      ,  5.49638205,  5.38888889,         nan],
        [ 7.9       ,  6.5       ,         nan,         nan],
        [ 6.94117647,  6.60666667,         nan,         nan]],

       [[        nan,         nan,  7.05128205,  8.        ],
        [        nan,  5.8       ,  6.60079051,  7.15151515],
        [        nan,  7.16666667,  7.18058691,  7.8       ],
        [        nan,  5.70056497,  5.9571263 ,  7.26666667],
        [        nan,  5.45652174,  4.94608196,  6.75      ],
        [        nan,  7.40841584,  7.53470437,  9.        ],
        [        nan,  6.67458432,  5.84818482,         nan],
        [10.25      ,  8.86538462,  8.54054054,         nan],
        [ 9.5       ,  7.72852234,  6.5       ,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan]],

       [[        nan,  7.        ,  6.34843206,  6.51428571],
        [        nan,         nan,         nan,         nan],
        [        nan,  6.625     ,  7.23863636,  7.30434783],
        [        nan,  6.8875    ,  6.88584475,  5.42857143],
        [ 5.        ,  7.3495935 ,  7.10810811,  7.11111111],
        [        nan,  6.00911854,  5.39846154,  4.88888889],
        [ 7.16666667,  6.41941392,  6.37323944,  4.        ],
        [ 7.61904762,  7.32038835,  7.14049587,         nan],
        [ 6.09433962,  5.55      ,  5.37662338,         nan],
        [ 9.28571429,  8.54901961,  9.        ,         nan],
        [ 7.94117647,  6.31555556,  4.        ,         nan]],

       [[        nan,         nan,  7.93670886,  7.        ],
        [        nan,  7.28571429,  5.85650224,  5.890625  ],
        [        nan,  6.70454545,  5.60034014,  5.80864198],
        [        nan,  7.15909091,  7.62318841,  7.13636364],
        [        nan,  5.47671233,  5.38625   ,  5.82352941],
        [        nan,  7.76579926,  7.44289694,  6.14285714],
        [ 6.07692308,  4.99514563,  4.82686567,         nan],
        [ 6.63636364,  6.79693487,  6.59090909,         nan],
        [ 7.59459459,  6.6167147 ,  5.85714286,         nan],
        [ 7.34545455,  6.26771654,  5.66666667,         nan],
        [ 8.83333333,  7.94915254,         nan,         nan]],

       [[        nan,  7.        ,  7.49473684,  7.85      ],
        [        nan,  9.5       ,  7.86713287,  7.17647059],
        [        nan,  7.5       ,  7.04577465,  7.65079365],
        [        nan,  5.40425532,  5.6       ,  5.80645161],
        [        nan,  5.81707317,  6.10872483,  7.14705882],
        [ 6.4       ,  7.55895197,  7.26609442,  9.25      ],
        [ 9.1       ,  5.90502793,  5.79389313,  6.66666667],
        [ 8.37142857,  7.51002865,  6.85057471,  6.        ],
        [ 7.22033898,  6.68637532,  6.19672131,         nan],
        [ 7.45945946,  7.26627219,  5.8       ,         nan],
        [ 8.27586207,  8.03076923,         nan,         nan]],

       [[        nan,         nan,  9.08571429,  8.35135135],
        [        nan,  5.69230769,  6.05343511,  6.2804878 ],
        [        nan,  6.375     ,  7.53020134,  6.67567568],
        [        nan,  6.86956522,  6.84228188,  6.51428571],
        [ 5.42857143,  6.05172414,  5.66004415,  6.13636364],
        [ 6.625     ,  6.03042596,  6.35820896,  7.63636364],
        [ 7.775     ,  7.96564885,  8.35238095,  7.16666667],
        [ 6.92063492,  6.00487013,  5.48672566,  4.5       ],
        [ 7.16666667,  5.84710744,  5.109375  ,         nan],
        [ 7.88888889,  8.76744186,  8.8       ,         nan],
        [ 6.65625   ,  6.16666667,  4.        ,         nan]],

       [[        nan,         nan,  8.56      ,  7.76829268],
        [        nan,  6.78571429,  6.20392157,  6.01675978],
        [        nan,  6.55555556,  5.98642534,  5.8409894 ],
        [ 4.        ,  6.87765957,  6.88157895,  7.06993007],
        [ 5.64285714,  6.12077295,  5.13729508,  5.16015625],
        [ 6.85915493,  7.07964602,  7.064     ,  7.41935484],
        [ 7.09090909,  7.11061947,  6.53125   ,  6.88888889],
        [ 5.41176471,  4.98837209,  5.08980583,  5.5       ],
        [ 7.18072289,  5.66212534,  5.52083333,         nan],
        [ 7.45882353,  7.54424779,  6.64285714,         nan],
        [ 7.64912281,  8.        ,         nan,         nan]],

       [[        nan,  6.8       ,  6.86163522,  6.68636364],
        [ 6.8       ,  7.4       ,  6.97810219,  6.25170068],
        [12.        ,  8.72727273,  7.96478873,  7.00719424],
        [ 5.        ,  6.31404959,  6.1377551 ,  6.20430108],
        [ 7.13043478,  7.60619469,  7.99514563,  8.26666667],
        [ 7.625     ,  7.05940594,  7.245     ,  6.625     ],
        [ 6.        ,  5.52818991,  5.92764858,  6.37931034],
        [ 7.5       ,  6.81617647,  6.61904762,  6.25      ],
        [ 7.77358491,  8.32335329,  8.72727273, 12.5       ],
        [ 7.79545455,  6.51282051,  6.37837838,  7.        ],
        [ 6.75961538,  5.75675676,         nan,         nan]],

       [[        nan,         nan,         nan,         nan],
        [        nan,  6.12087912,  6.51891892,  6.14935065],
        [        nan,  7.29230769,  6.21223022,  6.56680162],
        [10.14285714,  8.2247191 ,  7.71774194,  7.14285714],
        [ 5.89361702,  5.65326633,  5.07142857,  5.39163498],
        [ 7.92      ,  8.02970297,  7.91      ,  6.89361702],
        [ 5.98496241,  5.19129082,  5.31078224,  5.72093023],
        [ 6.21568627,  5.61852433,  6.75770925,  4.6       ],
        [ 8.64864865,  8.1125    ,  9.05882353,  6.2       ],
        [ 5.42268041,  5.29590018,  5.14364641,  4.        ],
        [ 7.58823529,  7.55357143,         nan,         nan]],

       [[        nan,         nan,         nan,         nan],
        [        nan,  7.66666667,  7.25641026,  7.13471503],
        [ 6.08      ,  6.89032258,  6.7627907 ,  6.28880866],
        [ 7.63157895,  7.25      ,  6.19469027,  7.36363636],
        [ 6.3968254 ,  6.61783439,  6.2406639 ,  6.912     ],
        [ 7.25      ,  6.17886179,  6.16595745,  6.68644068],
        [ 8.74736842,  7.84946237,  8.49122807,  8.05405405],
        [ 8.22058824,  8.02173913,  8.        ,  9.71428571],
        [ 6.62820513,  6.02083333,  6.66666667,  4.5       ],
        [ 5.84246575,  5.78807947,  4.82      ,         nan],
        [ 7.92571429,  8.21052632,         nan,         nan]],

       [[        nan,         nan,         nan,         nan],
        [ 7.22222222,  6.83333333,  7.15662651,  6.70652174],
        [ 5.13636364,  6.68421053,  7.41463415,  7.14583333],
        [ 7.75454545,  8.17924528,  7.04166667,  8.05421687],
        [ 6.15254237,  6.6875    ,  6.31818182,  6.31715771],
        [ 8.35643564,  8.08695652,  7.26666667,  7.64356436],
        [ 7.25210084,  6.89344262,  7.32061069,  6.46153846],
        [        nan,         nan,         nan,         nan],
        [ 6.73262032,  7.00662252,  8.73333333,  7.91176471],
        [ 7.35185185,  7.30769231,  6.33333333,  6.6       ],
        [ 7.3627451 ,  8.94117647,         nan,  9.23333333]],

       [[ 6.75      ,         nan,  6.42857143,  6.97432763],
        [        nan,         nan,         nan,         nan],
        [ 6.90987124,  6.91935484,  7.35714286,  7.0041841 ],
        [ 6.88700565,  7.22222222,  7.16216216,  7.24014337],
        [        nan,         nan,         nan,         nan],
        [ 5.84065934,  4.85245902,  4.90924956,  5.42375367],
        [        nan,         nan,         nan,         nan],
        [ 7.21287129,  6.78666667,  7.15079365,  6.70515098],
        [ 5.70491803,  6.11904762,  6.05263158,  6.66459627],
        [ 6.16375546,  7.125     ,  5.83333333,  6.88869258],
        [ 5.64964539,  5.45833333,         nan,  6.36482085]],

       [[        nan,         nan,         nan,         nan],
        [        nan,  7.94736842, 10.33333333,  7.97794118],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [ 5.86075949,  5.46808511,  5.28571429,  6.0328125 ],
        [        nan,         nan,         nan,         nan],
        [ 6.19926199,  6.15384615,  7.4       ,  6.19964974],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan]],

       [[        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,  7.01658768],
        [        nan,         nan,         nan,         nan],
        [ 7.26744186,  8.33333333,         nan,  7.51544196],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan]],

       [[        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,  6.31727125],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [ 6.84482759,         nan,         nan,  7.33491686],
        [        nan,         nan,         nan,         nan]],

       [[        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan]]])

In [10]:
classifier.shape

(18, 11, 4)